/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Xian.Common.DICOM {

using System;
using System.Text;

public class DcmAssociationConfigurationFile : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal DcmAssociationConfigurationFile(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(DcmAssociationConfigurationFile obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~DcmAssociationConfigurationFile() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      DCMTKPINVOKE.delete_DcmAssociationConfigurationFile(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public static OFCondition initialize(DcmAssociationConfiguration cfg, string filename) {
    return new OFCondition(DCMTKPINVOKE.DcmAssociationConfigurationFile_initialize(DcmAssociationConfiguration.getCPtr(cfg), filename), true);
  }

  public DcmAssociationConfigurationFile() : this(DCMTKPINVOKE.new_DcmAssociationConfigurationFile(), true) {
  }

}

}
