/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Xian.Common.DICOM {

using System;
using System.Text;

public class DcmByteString : DcmElement {
  private IntPtr swigCPtr;

  internal DcmByteString(IntPtr cPtr, bool cMemoryOwn) : base(DCMTKPINVOKE.DcmByteStringUpcast(cPtr), cMemoryOwn) {
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(DcmByteString obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  protected DcmByteString() : this(IntPtr.Zero, false) {
  }

  ~DcmByteString() {
    Dispose();
  }

  public override void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      DCMTKPINVOKE.delete_DcmByteString(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
    base.Dispose();
  }

  public DcmByteString(DcmTag tag, uint len) : this(DCMTKPINVOKE.new_DcmByteString__SWIG_0(DcmTag.getCPtr(tag), len), true) {
  }

  public DcmByteString(DcmTag tag) : this(DCMTKPINVOKE.new_DcmByteString__SWIG_1(DcmTag.getCPtr(tag)), true) {
  }

  public DcmByteString(DcmByteString old) : this(DCMTKPINVOKE.new_DcmByteString__SWIG_2(DcmByteString.getCPtr(old)), true) {
  }

  public override DcmEVR ident() {
    return (DcmEVR)DCMTKPINVOKE.DcmByteString_ident(swigCPtr);
  }

  public override OFCondition clear() {
    return new OFCondition(DCMTKPINVOKE.DcmByteString_clear(swigCPtr), true);
  }

  public override uint getVM() {
    return DCMTKPINVOKE.DcmByteString_getVM(swigCPtr);
  }

  public uint getRealLength() {
    return DCMTKPINVOKE.DcmByteString_getRealLength(swigCPtr);
  }

  public override uint getLength(E_TransferSyntax xfer, E_EncodingType enctype) {
    return DCMTKPINVOKE.DcmByteString_getLength__SWIG_0(swigCPtr, (int)xfer, (int)enctype);
  }

  public override uint getLength(E_TransferSyntax xfer) {
    return DCMTKPINVOKE.DcmByteString_getLength__SWIG_1(swigCPtr, (int)xfer);
  }

  public override uint getLength() {
    return DCMTKPINVOKE.DcmByteString_getLength__SWIG_2(swigCPtr);
  }

  public override void print(SWIGTYPE_p_ostream outStream, uint flags, int level, string pixelFileName, SWIGTYPE_p_size_t pixelCounter) {
    DCMTKPINVOKE.DcmByteString_print__SWIG_0(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream), flags, level, pixelFileName, SWIGTYPE_p_size_t.getCPtr(pixelCounter));
  }

  public override void print(SWIGTYPE_p_ostream outStream, uint flags, int level, string pixelFileName) {
    DCMTKPINVOKE.DcmByteString_print__SWIG_1(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream), flags, level, pixelFileName);
  }

  public override void print(SWIGTYPE_p_ostream outStream, uint flags, int level) {
    DCMTKPINVOKE.DcmByteString_print__SWIG_2(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream), flags, level);
  }

  public override void print(SWIGTYPE_p_ostream outStream, uint flags) {
    DCMTKPINVOKE.DcmByteString_print__SWIG_3(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream), flags);
  }

  public override void print(SWIGTYPE_p_ostream outStream) {
    DCMTKPINVOKE.DcmByteString_print__SWIG_4(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream));
  }

  public override OFCondition write(DcmOutputStream outStream, E_TransferSyntax writeXfer, E_EncodingType encodingType) {
    return new OFCondition(DCMTKPINVOKE.DcmByteString_write__SWIG_0(swigCPtr, DcmOutputStream.getCPtr(outStream), (int)writeXfer, (int)encodingType), true);
  }

  public override OFCondition write(DcmOutputStream outStream, E_TransferSyntax writeXfer) {
    return new OFCondition(DCMTKPINVOKE.DcmByteString_write__SWIG_1(swigCPtr, DcmOutputStream.getCPtr(outStream), (int)writeXfer), true);
  }

  public override OFCondition writeSignatureFormat(DcmOutputStream outStream, E_TransferSyntax writeXfer, E_EncodingType encodingType) {
    return new OFCondition(DCMTKPINVOKE.DcmByteString_writeSignatureFormat__SWIG_0(swigCPtr, DcmOutputStream.getCPtr(outStream), (int)writeXfer, (int)encodingType), true);
  }

  public override OFCondition writeSignatureFormat(DcmOutputStream outStream, E_TransferSyntax writeXfer) {
    return new OFCondition(DCMTKPINVOKE.DcmByteString_writeSignatureFormat__SWIG_1(swigCPtr, DcmOutputStream.getCPtr(outStream), (int)writeXfer), true);
  }

  public override OFCondition getOFString(StringBuilder stringVal, uint pos, bool normalize) {
    return new OFCondition(DCMTKPINVOKE.DcmByteString_getOFString__SWIG_0(swigCPtr, stringVal, pos, normalize), true);
  }

  public override OFCondition getOFString(StringBuilder stringVal, uint pos) {
    return new OFCondition(DCMTKPINVOKE.DcmByteString_getOFString__SWIG_1(swigCPtr, stringVal, pos), true);
  }

  public override OFCondition getString(ref IntPtr stringVal) {
    return new OFCondition(DCMTKPINVOKE.DcmByteString_getString(swigCPtr, ref stringVal), true);
  }

  public override OFCondition putString(string stringVal) {
    return new OFCondition(DCMTKPINVOKE.DcmByteString_putString(swigCPtr, stringVal), true);
  }

  public override OFCondition putOFStringArray(string stringVal) {
    return new OFCondition(DCMTKPINVOKE.DcmByteString_putOFStringArray(swigCPtr, stringVal), true);
  }

  public override OFCondition verify(bool autocorrect) {
    return new OFCondition(DCMTKPINVOKE.DcmByteString_verify__SWIG_0(swigCPtr, autocorrect), true);
  }

  public override OFCondition verify() {
    return new OFCondition(DCMTKPINVOKE.DcmByteString_verify__SWIG_1(swigCPtr), true);
  }

}

}
