/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Xian.Common.DICOM {

using System;
using System.Text;

public class GlobalDcmDataDictionary : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal GlobalDcmDataDictionary(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(GlobalDcmDataDictionary obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  protected GlobalDcmDataDictionary() : this(IntPtr.Zero, false) {
  }

  ~GlobalDcmDataDictionary() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      DCMTKPINVOKE.delete_GlobalDcmDataDictionary(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public GlobalDcmDataDictionary(bool loadBuiltin, bool loadExternal) : this(DCMTKPINVOKE.new_GlobalDcmDataDictionary(loadBuiltin, loadExternal), true) {
  }

  public DcmDataDictionary rdlock() {
    return new DcmDataDictionary(DCMTKPINVOKE.GlobalDcmDataDictionary_rdlock(swigCPtr), false);
  }

  public DcmDataDictionary wrlock() {
    return new DcmDataDictionary(DCMTKPINVOKE.GlobalDcmDataDictionary_wrlock(swigCPtr), false);
  }

  public void unlock() {
    DCMTKPINVOKE.GlobalDcmDataDictionary_unlock(swigCPtr);
  }

  public bool isDictionaryLoaded() {
    return DCMTKPINVOKE.GlobalDcmDataDictionary_isDictionaryLoaded(swigCPtr);
  }

  public void clear() {
    DCMTKPINVOKE.GlobalDcmDataDictionary_clear(swigCPtr);
  }

}

}
