/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Xian.Common.DICOM {

using System;
using System.Text;

public class OFDate : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal OFDate(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(OFDate obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~OFDate() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      DCMTKPINVOKE.delete_OFDate(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public OFDate() : this(DCMTKPINVOKE.new_OFDate__SWIG_0(), true) {
  }

  public OFDate(OFDate dateVal) : this(DCMTKPINVOKE.new_OFDate__SWIG_1(OFDate.getCPtr(dateVal)), true) {
  }

  public OFDate(uint year, uint month, uint day) : this(DCMTKPINVOKE.new_OFDate__SWIG_2(year, month, day), true) {
  }

  public virtual void clear() {
    DCMTKPINVOKE.OFDate_clear(swigCPtr);
  }

  public virtual bool isValid() {
    return DCMTKPINVOKE.OFDate_isValid(swigCPtr);
  }

  public bool setDate(uint year, uint month, uint day) {
    return DCMTKPINVOKE.OFDate_setDate(swigCPtr, year, month, day);
  }

  public bool setYear(uint year) {
    return DCMTKPINVOKE.OFDate_setYear(swigCPtr, year);
  }

  public bool setMonth(uint month) {
    return DCMTKPINVOKE.OFDate_setMonth(swigCPtr, month);
  }

  public bool setDay(uint day) {
    return DCMTKPINVOKE.OFDate_setDay(swigCPtr, day);
  }

  public bool setCurrentDate() {
    return DCMTKPINVOKE.OFDate_setCurrentDate(swigCPtr);
  }

  public bool setISOFormattedDate(string formattedDate) {
    return DCMTKPINVOKE.OFDate_setISOFormattedDate(swigCPtr, formattedDate);
  }

  public uint getYear() {
    return DCMTKPINVOKE.OFDate_getYear(swigCPtr);
  }

  public uint getMonth() {
    return DCMTKPINVOKE.OFDate_getMonth(swigCPtr);
  }

  public uint getDay() {
    return DCMTKPINVOKE.OFDate_getDay(swigCPtr);
  }

  public bool getISOFormattedDate(StringBuilder formattedDate, bool showDelimiter) {
    return DCMTKPINVOKE.OFDate_getISOFormattedDate__SWIG_0(swigCPtr, formattedDate, showDelimiter);
  }

  public bool getISOFormattedDate(StringBuilder formattedDate) {
    return DCMTKPINVOKE.OFDate_getISOFormattedDate__SWIG_1(swigCPtr, formattedDate);
  }

  public static OFDate getCurrentDate() {
    return new OFDate(DCMTKPINVOKE.OFDate_getCurrentDate(), true);
  }

}

}
