/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ClearCanvas.Common.Dicom {

using System;
using System.Text;

public class DcmAssociationConfiguration : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal DcmAssociationConfiguration(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(DcmAssociationConfiguration obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~DcmAssociationConfiguration() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      DCMTKPINVOKE.delete_DcmAssociationConfiguration(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public DcmAssociationConfiguration() : this(DCMTKPINVOKE.new_DcmAssociationConfiguration(), true) {
  }

  public OFCondition setAssociationParameters(string profile, T_ASC_Parameters parameters) {
    return new OFCondition(DCMTKPINVOKE.DcmAssociationConfiguration_setAssociationParameters(swigCPtr, profile, T_ASC_Parameters.getCPtr(parameters)), true);
  }

  public OFCondition evaluateAssociationParameters(string profile, T_ASC_Association assoc) {
    return new OFCondition(DCMTKPINVOKE.DcmAssociationConfiguration_evaluateAssociationParameters(swigCPtr, profile, T_ASC_Association.getCPtr(assoc)), true);
  }

  public OFCondition addTransferSyntax(string key, string transferSyntaxUID) {
    return new OFCondition(DCMTKPINVOKE.DcmAssociationConfiguration_addTransferSyntax(swigCPtr, key, transferSyntaxUID), true);
  }

  public OFCondition addPresentationContext(string key, string abstractSyntaxUID, string transferSyntaxKey) {
    return new OFCondition(DCMTKPINVOKE.DcmAssociationConfiguration_addPresentationContext(swigCPtr, key, abstractSyntaxUID, transferSyntaxKey), true);
  }

  public OFCondition addRole(string key, string abstractSyntaxUID, T_ASC_SC_ROLE role) {
    return new OFCondition(DCMTKPINVOKE.DcmAssociationConfiguration_addRole(swigCPtr, key, abstractSyntaxUID, (int)role), true);
  }

  public OFCondition addExtendedNegotiation(string key, string abstractSyntaxUID, SWIGTYPE_p_unsigned_char rawData, uint length) {
    return new OFCondition(DCMTKPINVOKE.DcmAssociationConfiguration_addExtendedNegotiation(swigCPtr, key, abstractSyntaxUID, SWIGTYPE_p_unsigned_char.getCPtr(rawData), length), true);
  }

  public OFCondition addProfile(string key, string presentationContextKey, string roleSelectionKey, string extendedNegotiationKey) {
    return new OFCondition(DCMTKPINVOKE.DcmAssociationConfiguration_addProfile__SWIG_0(swigCPtr, key, presentationContextKey, roleSelectionKey, extendedNegotiationKey), true);
  }

  public OFCondition addProfile(string key, string presentationContextKey, string roleSelectionKey) {
    return new OFCondition(DCMTKPINVOKE.DcmAssociationConfiguration_addProfile__SWIG_1(swigCPtr, key, presentationContextKey, roleSelectionKey), true);
  }

  public OFCondition addProfile(string key, string presentationContextKey) {
    return new OFCondition(DCMTKPINVOKE.DcmAssociationConfiguration_addProfile__SWIG_2(swigCPtr, key, presentationContextKey), true);
  }

  public bool isKnownProfile(string key) {
    return DCMTKPINVOKE.DcmAssociationConfiguration_isKnownProfile(swigCPtr, key);
  }

  public bool isValidSCPProfile(string key) {
    return DCMTKPINVOKE.DcmAssociationConfiguration_isValidSCPProfile(swigCPtr, key);
  }

}

}
