/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ClearCanvas.Common.Dicom {

using System;
using System.Text;
using System.Runtime.InteropServices;

public class DcmInputStream : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DcmInputStream(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DcmInputStream obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DcmInputStream() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      DCMTKPINVOKE.delete_DcmInputStream(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public virtual bool good() {
    bool ret = DCMTKPINVOKE.DcmInputStream_good(swigCPtr);
    return ret;
  }

  public virtual OFCondition status() {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmInputStream_status(swigCPtr), true);
    return ret;
  }

  public virtual bool eos() {
    bool ret = DCMTKPINVOKE.DcmInputStream_eos(swigCPtr);
    return ret;
  }

  public virtual uint avail() {
    uint ret = DCMTKPINVOKE.DcmInputStream_avail(swigCPtr);
    return ret;
  }

  public virtual uint read(SWIGTYPE_p_void buf, uint buflen) {
    uint ret = DCMTKPINVOKE.DcmInputStream_read(swigCPtr, SWIGTYPE_p_void.getCPtr(buf), buflen);
    return ret;
  }

  public virtual uint skip(uint skiplen) {
    uint ret = DCMTKPINVOKE.DcmInputStream_skip(swigCPtr, skiplen);
    return ret;
  }

  public virtual uint tell() {
    uint ret = DCMTKPINVOKE.DcmInputStream_tell(swigCPtr);
    return ret;
  }

  public virtual OFCondition installCompressionFilter(E_StreamCompression filterType) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmInputStream_installCompressionFilter(swigCPtr, (int)filterType), true);
    return ret;
  }

  public virtual DcmInputStreamFactory newFactory() {
    IntPtr cPtr = DCMTKPINVOKE.DcmInputStream_newFactory(swigCPtr);
    DcmInputStreamFactory ret = (cPtr == IntPtr.Zero) ? null : new DcmInputStreamFactory(cPtr, false);
    return ret;
  }

  public virtual void mark() {
    DCMTKPINVOKE.DcmInputStream_mark(swigCPtr);
  }

  public virtual void putback() {
    DCMTKPINVOKE.DcmInputStream_putback(swigCPtr);
  }

}

}
