/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ClearCanvas.Common.Dicom {

using System;
using System.Text;
using System.Runtime.InteropServices;

public class DcmPixelSequence : DcmSequenceOfItems {
  private HandleRef swigCPtr;

  internal DcmPixelSequence(IntPtr cPtr, bool cMemoryOwn) : base(DCMTKPINVOKE.DcmPixelSequenceUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DcmPixelSequence obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DcmPixelSequence() {
    Dispose();
  }

  public override void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      DCMTKPINVOKE.delete_DcmPixelSequence(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
    base.Dispose();
  }

  public DcmPixelSequence(DcmTag tag, uint len) : this(DCMTKPINVOKE.new_DcmPixelSequence__SWIG_0(DcmTag.getCPtr(tag), len), true) {
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public DcmPixelSequence(DcmTag tag) : this(DCMTKPINVOKE.new_DcmPixelSequence__SWIG_1(DcmTag.getCPtr(tag)), true) {
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public DcmPixelSequence(DcmPixelSequence old) : this(DCMTKPINVOKE.new_DcmPixelSequence__SWIG_2(DcmPixelSequence.getCPtr(old)), true) {
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override DcmEVR ident() {
    DcmEVR ret = (DcmEVR)DCMTKPINVOKE.DcmPixelSequence_ident(swigCPtr);
    return ret;
  }

  public override void print(SWIGTYPE_p_ostream outStream, uint flags, int level, string pixelFileName, SWIGTYPE_p_size_t pixelCounter) {
    DCMTKPINVOKE.DcmPixelSequence_print__SWIG_0(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream), flags, level, pixelFileName, SWIGTYPE_p_size_t.getCPtr(pixelCounter));
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void print(SWIGTYPE_p_ostream outStream, uint flags, int level, string pixelFileName) {
    DCMTKPINVOKE.DcmPixelSequence_print__SWIG_1(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream), flags, level, pixelFileName);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void print(SWIGTYPE_p_ostream outStream, uint flags, int level) {
    DCMTKPINVOKE.DcmPixelSequence_print__SWIG_2(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream), flags, level);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void print(SWIGTYPE_p_ostream outStream, uint flags) {
    DCMTKPINVOKE.DcmPixelSequence_print__SWIG_3(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream), flags);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void print(SWIGTYPE_p_ostream outStream) {
    DCMTKPINVOKE.DcmPixelSequence_print__SWIG_4(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream));
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override uint calcElementLength(E_TransferSyntax xfer, E_EncodingType enctype) {
    uint ret = DCMTKPINVOKE.DcmPixelSequence_calcElementLength(swigCPtr, (int)xfer, (int)enctype);
    return ret;
  }

  public virtual OFCondition insert(SWIGTYPE_p_DcmPixelItem item, uint where) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmPixelSequence_insert__SWIG_0(swigCPtr, SWIGTYPE_p_DcmPixelItem.getCPtr(item), where), true);
    return ret;
  }

  public virtual OFCondition insert(SWIGTYPE_p_DcmPixelItem item) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmPixelSequence_insert__SWIG_1(swigCPtr, SWIGTYPE_p_DcmPixelItem.getCPtr(item)), true);
    return ret;
  }

  public virtual OFCondition getItem(SWIGTYPE_p_p_DcmPixelItem item, uint num) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmPixelSequence_getItem(swigCPtr, SWIGTYPE_p_p_DcmPixelItem.getCPtr(item), num), true);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual OFCondition remove(SWIGTYPE_p_p_DcmPixelItem item, uint num) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmPixelSequence_remove__SWIG_0(swigCPtr, SWIGTYPE_p_p_DcmPixelItem.getCPtr(item), num), true);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual OFCondition remove(SWIGTYPE_p_DcmPixelItem item) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmPixelSequence_remove__SWIG_1(swigCPtr, SWIGTYPE_p_DcmPixelItem.getCPtr(item)), true);
    return ret;
  }

  public OFCondition changeXfer(E_TransferSyntax newXfer) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmPixelSequence_changeXfer(swigCPtr, (int)newXfer), true);
    return ret;
  }

  public override bool canWriteXfer(E_TransferSyntax newXfer, E_TransferSyntax oldXfer) {
    bool ret = DCMTKPINVOKE.DcmPixelSequence_canWriteXfer(swigCPtr, (int)newXfer, (int)oldXfer);
    return ret;
  }

  public override OFCondition read(DcmInputStream inStream, E_TransferSyntax ixfer, E_GrpLenEncoding glenc, uint maxReadLength) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmPixelSequence_read__SWIG_0(swigCPtr, DcmInputStream.getCPtr(inStream), (int)ixfer, (int)glenc, maxReadLength), true);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override OFCondition read(DcmInputStream inStream, E_TransferSyntax ixfer, E_GrpLenEncoding glenc) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmPixelSequence_read__SWIG_1(swigCPtr, DcmInputStream.getCPtr(inStream), (int)ixfer, (int)glenc), true);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override OFCondition read(DcmInputStream inStream, E_TransferSyntax ixfer) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmPixelSequence_read__SWIG_2(swigCPtr, DcmInputStream.getCPtr(inStream), (int)ixfer), true);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override OFCondition write(DcmOutputStream outStream, E_TransferSyntax oxfer, E_EncodingType arg2) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmPixelSequence_write(swigCPtr, DcmOutputStream.getCPtr(outStream), (int)oxfer, (int)arg2), true);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override OFCondition writeSignatureFormat(DcmOutputStream outStream, E_TransferSyntax oxfer, E_EncodingType enctype) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmPixelSequence_writeSignatureFormat__SWIG_0(swigCPtr, DcmOutputStream.getCPtr(outStream), (int)oxfer, (int)enctype), true);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override OFCondition writeSignatureFormat(DcmOutputStream outStream, E_TransferSyntax oxfer) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmPixelSequence_writeSignatureFormat__SWIG_1(swigCPtr, DcmOutputStream.getCPtr(outStream), (int)oxfer), true);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual OFCondition storeCompressedFrame(SWIGTYPE_p_DcmOffsetList offsetList, byte[] compressedData, uint compressedLen, uint fragmentSize) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmPixelSequence_storeCompressedFrame(swigCPtr, SWIGTYPE_p_DcmOffsetList.getCPtr(offsetList), compressedData, compressedLen, fragmentSize), true);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
