/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ClearCanvas.Common.DICOM {

using System;
using System.Text;

public class DcmTagKey : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal DcmTagKey(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(DcmTagKey obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~DcmTagKey() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      DCMTKPINVOKE.delete_DcmTagKey(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public DcmTagKey() : this(DCMTKPINVOKE.new_DcmTagKey__SWIG_0(), true) {
  }

  public DcmTagKey(DcmTagKey key) : this(DCMTKPINVOKE.new_DcmTagKey__SWIG_1(DcmTagKey.getCPtr(key)), true) {
  }

  public DcmTagKey(ushort g, ushort e) : this(DCMTKPINVOKE.new_DcmTagKey__SWIG_2(g, e), true) {
  }

  public void set(DcmTagKey key) {
    DCMTKPINVOKE.DcmTagKey_set__SWIG_0(swigCPtr, DcmTagKey.getCPtr(key));
  }

  public void set(ushort g, ushort e) {
    DCMTKPINVOKE.DcmTagKey_set__SWIG_1(swigCPtr, g, e);
  }

  public void setGroup(ushort g) {
    DCMTKPINVOKE.DcmTagKey_setGroup(swigCPtr, g);
  }

  public void setElement(ushort e) {
    DCMTKPINVOKE.DcmTagKey_setElement(swigCPtr, e);
  }

  public ushort getGroup() {
    return DCMTKPINVOKE.DcmTagKey_getGroup(swigCPtr);
  }

  public ushort getElement() {
    return DCMTKPINVOKE.DcmTagKey_getElement(swigCPtr);
  }

  public uint hash() {
    return DCMTKPINVOKE.DcmTagKey_hash(swigCPtr);
  }

  public string toString() {
    return DCMTKPINVOKE.DcmTagKey_toString(swigCPtr);
  }

  public bool isSignableTag() {
    return DCMTKPINVOKE.DcmTagKey_isSignableTag(swigCPtr);
  }

}

}
