/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ClearCanvas.Common.Dicom {

using System;
using System.Text;

public class OFConditionString : OFConditionBase {
  private IntPtr swigCPtr;

  internal OFConditionString(IntPtr cPtr, bool cMemoryOwn) : base(DCMTKPINVOKE.OFConditionStringUpcast(cPtr), cMemoryOwn) {
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(OFConditionString obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  protected OFConditionString() : this(IntPtr.Zero, false) {
  }

  ~OFConditionString() {
    Dispose();
  }

  public override void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      DCMTKPINVOKE.delete_OFConditionString(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
    base.Dispose();
  }

  public OFConditionString(ushort aModule, ushort aCode, OFStatus aStatus, string aText) : this(DCMTKPINVOKE.new_OFConditionString__SWIG_0(aModule, aCode, (int)aStatus, aText), true) {
  }

  public OFConditionString(OFConditionString arg) : this(DCMTKPINVOKE.new_OFConditionString__SWIG_1(OFConditionString.getCPtr(arg)), true) {
  }

  public override OFConditionBase clone() {
    IntPtr cPtr = DCMTKPINVOKE.OFConditionString_clone(swigCPtr);
    return (cPtr == IntPtr.Zero) ? null : new OFConditionBase(cPtr, false);
  }

  public override uint codeAndModule() {
    return DCMTKPINVOKE.OFConditionString_codeAndModule(swigCPtr);
  }

  public override OFStatus status() {
    return (OFStatus)DCMTKPINVOKE.OFConditionString_status(swigCPtr);
  }

  public override string text() {
    return DCMTKPINVOKE.OFConditionString_text(swigCPtr);
  }

  public override bool deletable() {
    return DCMTKPINVOKE.OFConditionString_deletable(swigCPtr);
  }

}

}
