/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ClearCanvas.Common.Dicom {

using System;
using System.Text;

public class T_DIMSE_StoreProgress : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal T_DIMSE_StoreProgress(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(T_DIMSE_StoreProgress obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~T_DIMSE_StoreProgress() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      DCMTKPINVOKE.delete_T_DIMSE_StoreProgress(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public T_DIMSE_StoreProgressState state {
    set {
      DCMTKPINVOKE.set_T_DIMSE_StoreProgress_state(swigCPtr, (int)value);
    } 
    get {
      return (T_DIMSE_StoreProgressState)DCMTKPINVOKE.get_T_DIMSE_StoreProgress_state(swigCPtr);
    } 
  }

  public int callbackCount {
    set {
      DCMTKPINVOKE.set_T_DIMSE_StoreProgress_callbackCount(swigCPtr, value);
    } 
    get {
      return DCMTKPINVOKE.get_T_DIMSE_StoreProgress_callbackCount(swigCPtr);
    } 
  }

  public int progressBytes {
    set {
      DCMTKPINVOKE.set_T_DIMSE_StoreProgress_progressBytes(swigCPtr, value);
    } 
    get {
      return DCMTKPINVOKE.get_T_DIMSE_StoreProgress_progressBytes(swigCPtr);
    } 
  }

  public int totalBytes {
    set {
      DCMTKPINVOKE.set_T_DIMSE_StoreProgress_totalBytes(swigCPtr, value);
    } 
    get {
      return DCMTKPINVOKE.get_T_DIMSE_StoreProgress_totalBytes(swigCPtr);
    } 
  }

  public T_DIMSE_StoreProgress() : this(DCMTKPINVOKE.new_T_DIMSE_StoreProgress(), true) {
  }

}

}
