/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ClearCanvas.Common.Dicom {

using System;
using System.Text;

public class T_DIMSE_DetectedCancelParameters : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal T_DIMSE_DetectedCancelParameters(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(T_DIMSE_DetectedCancelParameters obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~T_DIMSE_DetectedCancelParameters() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      DCMTKPINVOKE.delete_T_DIMSE_DetectedCancelParameters(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public bool cancelEncountered {
    set {
      DCMTKPINVOKE.set_T_DIMSE_DetectedCancelParameters_cancelEncountered(swigCPtr, value);
    } 
    get {
      return DCMTKPINVOKE.get_T_DIMSE_DetectedCancelParameters_cancelEncountered(swigCPtr);
    } 
  }

  public SWIGTYPE_p_DUL_PRESENTATIONCONTEXTID presId {
    set {
      DCMTKPINVOKE.set_T_DIMSE_DetectedCancelParameters_presId(swigCPtr, SWIGTYPE_p_DUL_PRESENTATIONCONTEXTID.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p_DUL_PRESENTATIONCONTEXTID(DCMTKPINVOKE.get_T_DIMSE_DetectedCancelParameters_presId(swigCPtr), true);
    } 
  }

  public T_DIMSE_C_CancelRQ req {
    set {
      DCMTKPINVOKE.set_T_DIMSE_DetectedCancelParameters_req(swigCPtr, T_DIMSE_C_CancelRQ.getCPtr(value));
    } 
    get {
      IntPtr cPtr = DCMTKPINVOKE.get_T_DIMSE_DetectedCancelParameters_req(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new T_DIMSE_C_CancelRQ(cPtr, false);
    } 
  }

  public T_DIMSE_DetectedCancelParameters() : this(DCMTKPINVOKE.new_T_DIMSE_DetectedCancelParameters(), true) {
  }

}

}
