//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4005
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageServer.Web.Application.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageServer.Web.Application.App_GlobalResources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform the action at this time: {0}. Please try again later..
        /// </summary>
        public static string ActionNotAllowedAtThisTime {
            get {
                return ResourceManager.GetString("ActionNotAllowedAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device {0} has entries in the WorkQueue and cannot be deleted..
        /// </summary>
        public static string AdminDevices_DeleteDevice_PendingWorkQueue {
            get {
                return ResourceManager.GetString("AdminDevices_DeleteDevice_PendingWorkQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete this server partition. This could mean there are studies on this partition.
        ///
        ///Please check the log file or contact the server administrator..
        /// </summary>
        public static string AdminPartition_DeletePartition_Failed {
            get {
                return ResourceManager.GetString("AdminPartition_DeletePartition_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete User Group &quot;{0}&quot; because there are users who are a part of this group..
        /// </summary>
        public static string AdminUserGroups_DeleteUserGroupFailed {
            get {
                return ResourceManager.GetString("AdminUserGroups_DeleteUserGroupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete this alert item..
        /// </summary>
        public static string AlertDeleteFailed {
            get {
                return ResourceManager.GetString("AlertDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete this alert item.&lt;br&gt;Error: {0}.
        /// </summary>
        public static string AlertDeleteFailed_WithException {
            get {
                return ResourceManager.GetString("AlertDeleteFailed_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This alert item is no longer available in the system..
        /// </summary>
        public static string AlertNotAvailable {
            get {
                return ResourceManager.GetString("AlertNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageServer Authorization Failed..
        /// </summary>
        public static string AuthorizationError {
            get {
                return ResourceManager.GetString("AuthorizationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to contact the authentication and authorization server..
        /// </summary>
        public static string CannotContactEnterpriseServer {
            get {
                return ResourceManager.GetString("CannotContactEnterpriseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies are currently disabled on your browser..
        /// </summary>
        public static string CookiesAreDisabled {
            get {
                return ResourceManager.GetString("CookiesAreDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearCanvas ImageServer requires your browser to accept Cookies.  Please enable Cookies on your browser and click here to try again..
        /// </summary>
        public static string CookiesAreDisabledLongDescription {
            get {
                return ResourceManager.GetString("CookiesAreDisabledLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the study. See server log for more details..
        /// </summary>
        public static string DeleteStudyError {
            get {
                return ResourceManager.GetString("DeleteStudyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error. Please check all tabs for indicated errors and correct before submitting changes..
        /// </summary>
        public static string EditDeviceValidationError {
            get {
                return ResourceManager.GetString("EditDeviceValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error. Please check all tabs for indicated errors and correct before submitting changes..
        /// </summary>
        public static string EditFileSystemValidationError {
            get {
                return ResourceManager.GetString("EditFileSystemValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error. Please check all tabs for indicated errors and correct before submitting changes..
        /// </summary>
        public static string EditPartitionValidationError {
            get {
                return ResourceManager.GetString("EditPartitionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error. Please check all tabs for indicated errors and correct before submitting changes..
        /// </summary>
        public static string EditServerRuleValidationError {
            get {
                return ResourceManager.GetString("EditServerRuleValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error. Please check all tabs for indicated errors and correct before submitting changes..
        /// </summary>
        public static string EditStudyValidationError {
            get {
                return ResourceManager.GetString("EditStudyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To include the ImageServer&apos;s error message, click here..
        /// </summary>
        public static string ErrorShowStackTraceMessage {
            get {
                return ResourceManager.GetString("ErrorShowStackTraceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is being displayed because the ClearCanvas ImageServer encountered a situation that was unexpected. The resulting error has been recorded for future analysis. 
        ///
        ///If you would like to report the error, please post to one of the forums listed below and provide any information you think will be helpful in handling this situation in the future..
        /// </summary>
        public static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javascript is currently disabled on your browser..
        /// </summary>
        public static string JavascriptIsDisabled {
            get {
                return ResourceManager.GetString("JavascriptIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearCanvas ImageServer requires Javascript in order to run. Please enable Javascript on your browser and click here to try again.
        /// </summary>
        public static string JavascriptIsDisabledLongDescription {
            get {
                return ResourceManager.GetString("JavascriptIsDisabledLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User ID or Password..
        /// </summary>
        public static string LoginInvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("LoginInvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error: Multiple Partitions exist with AE title {0}.
        /// </summary>
        public static string MultiplePartitionsExistWithAETitle {
            get {
                return ResourceManager.GetString("MultiplePartitionsExistWithAETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred resetting the password. Password has not been changed..
        /// </summary>
        public static string PasswordResetFailed {
            get {
                return ResourceManager.GetString("PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided passwords do not match.&lt;br/&gt;Please retype your passwords and try again..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided passwords don&apos;t match. 
        ///Please retype your passwords and try again..
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageServer session timed out..
        /// </summary>
        public static string SessionTimedout {
            get {
                return ResourceManager.GetString("SessionTimedout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is being displayed because there has been no activity in the past {0} minute(s). For security purposes, your ImageServer session has been closed. Please login again to continue using ClearCanvas ImageServer. .
        /// </summary>
        public static string SessionTimedoutLongDescription {
            get {
                return ResourceManager.GetString("SessionTimedoutLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened that the ImageServer was unprepared for..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is being displayed because the ClearCanvas ImageServer encountered an error authorizing user with ID &quot;{0}&quot;.
        /// </summary>
        public static string WebAuthorizationErrorDescription {
            get {
                return ResourceManager.GetString("WebAuthorizationErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is being displayed because there has been no activity in the past {0} minute(s). For security purposes, your ImageServer session has been closed..
        /// </summary>
        public static string WebViewerSessionTimedoutLongDescription {
            get {
                return ResourceManager.GetString("WebViewerSessionTimedoutLongDescription", resourceCulture);
            }
        }
    }
}
