#region License

// Copyright (c) 2006-2009, ClearCanvas Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without modification, 
// are permitted provided that the following conditions are met:
//
//    * Redistributions of source code must retain the above copyright notice, 
//      this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above copyright notice, 
//      this list of conditions and the following disclaimer in the documentation 
//      and/or other materials provided with the distribution.
//    * Neither the name of ClearCanvas Inc. nor the names of its contributors 
//      may be used to endorse or promote products derived from this software without 
//      specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR 
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, 
// OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE 
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
// HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
// ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
// OF SUCH DAMAGE.

#endregion

// This file is auto-generated by the ClearCanvas.Model.SqlServer2005.CodeGenerator project.

namespace ClearCanvas.ImageServer.Model
{
    using System;
    using System.Xml;
    using ClearCanvas.Enterprise.Core;
    using ClearCanvas.ImageServer.Enterprise;
    using ClearCanvas.ImageServer.Model.EntityBrokers;

    [Serializable]
    public partial class Device: ServerEntity
    {
        #region Constructors
        public Device():base("Device")
        {}
        public Device(
             System.String _aeTitle_
            ,System.Boolean _allowAutoRoute_
            ,System.Boolean _allowQuery_
            ,System.Boolean _allowRetrieve_
            ,System.Boolean _allowStorage_
            ,System.String _description_
            ,System.Boolean _dhcp_
            ,System.Boolean _enabled_
            ,System.String _ipAddress_
            ,System.Int32 _port_
            ,ClearCanvas.ImageServer.Enterprise.ServerEntityKey _serverPartitionKey_
            ,System.Int16 _throttleMaxConnections_
            ):base("Device")
        {
            _aeTitle = _aeTitle_;
            _allowAutoRoute = _allowAutoRoute_;
            _allowQuery = _allowQuery_;
            _allowRetrieve = _allowRetrieve_;
            _allowStorage = _allowStorage_;
            _description = _description_;
            _dhcp = _dhcp_;
            _enabled = _enabled_;
            _ipAddress = _ipAddress_;
            _port = _port_;
            _serverPartitionKey = _serverPartitionKey_;
            _throttleMaxConnections = _throttleMaxConnections_;
        }
        #endregion

        #region Private Members
        private String _aeTitle;
        private Boolean _allowAutoRoute;
        private Boolean _allowQuery;
        private Boolean _allowRetrieve;
        private Boolean _allowStorage;
        private String _description;
        private Boolean _dhcp;
        private Boolean _enabled;
        private String _ipAddress;
        private Int32 _port;
        private ServerEntityKey _serverPartitionKey;
        private Int16 _throttleMaxConnections;
        #endregion

        #region Public Properties
        [EntityFieldDatabaseMappingAttribute(TableName="Device", ColumnName="AeTitle")]
        public String AeTitle
        {
        get { return _aeTitle; }
        set { _aeTitle = value; }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Device", ColumnName="AllowAutoRoute")]
        public Boolean AllowAutoRoute
        {
        get { return _allowAutoRoute; }
        set { _allowAutoRoute = value; }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Device", ColumnName="AllowQuery")]
        public Boolean AllowQuery
        {
        get { return _allowQuery; }
        set { _allowQuery = value; }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Device", ColumnName="AllowRetrieve")]
        public Boolean AllowRetrieve
        {
        get { return _allowRetrieve; }
        set { _allowRetrieve = value; }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Device", ColumnName="AllowStorage")]
        public Boolean AllowStorage
        {
        get { return _allowStorage; }
        set { _allowStorage = value; }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Device", ColumnName="Description")]
        public String Description
        {
        get { return _description; }
        set { _description = value; }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Device", ColumnName="Dhcp")]
        public Boolean Dhcp
        {
        get { return _dhcp; }
        set { _dhcp = value; }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Device", ColumnName="Enabled")]
        public Boolean Enabled
        {
        get { return _enabled; }
        set { _enabled = value; }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Device", ColumnName="IpAddress")]
        public String IpAddress
        {
        get { return _ipAddress; }
        set { _ipAddress = value; }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Device", ColumnName="Port")]
        public Int32 Port
        {
        get { return _port; }
        set { _port = value; }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Device", ColumnName="ServerPartitionGUID")]
        public ServerEntityKey ServerPartitionKey
        {
        get { return _serverPartitionKey; }
        set { _serverPartitionKey = value; }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Device", ColumnName="ThrottleMaxConnections")]
        public Int16 ThrottleMaxConnections
        {
        get { return _throttleMaxConnections; }
        set { _throttleMaxConnections = value; }
        }
        #endregion

        #region Static Methods
        static public Device Load(ServerEntityKey key)
        {
            using (IReadContext read = PersistentStoreRegistry.GetDefaultStore().OpenReadContext())
            {
                return Load(read, key);
            }
        }
        static public Device Load(IPersistenceContext read, ServerEntityKey key)
        {
            IDeviceEntityBroker broker = read.GetBroker<IDeviceEntityBroker>();
            Device theObject = broker.Load(key);
            return theObject;
        }
        static public Device Insert(Device entity)
        {
            using (IUpdateContext update = PersistentStoreRegistry.GetDefaultStore().OpenUpdateContext(UpdateContextSyncMode.Flush))
            {
                Device newEntity = Insert(update, entity);
                update.Commit();
                return newEntity;
            }
        }
        static public Device Insert(IUpdateContext update, Device entity)
        {
            IDeviceEntityBroker broker = update.GetBroker<IDeviceEntityBroker>();
            DeviceUpdateColumns updateColumns = new DeviceUpdateColumns();
            updateColumns.AeTitle = entity.AeTitle;
            updateColumns.AllowAutoRoute = entity.AllowAutoRoute;
            updateColumns.AllowQuery = entity.AllowQuery;
            updateColumns.AllowRetrieve = entity.AllowRetrieve;
            updateColumns.AllowStorage = entity.AllowStorage;
            updateColumns.Description = entity.Description;
            updateColumns.Dhcp = entity.Dhcp;
            updateColumns.Enabled = entity.Enabled;
            updateColumns.IpAddress = entity.IpAddress;
            updateColumns.Port = entity.Port;
            updateColumns.ServerPartitionKey = entity.ServerPartitionKey;
            updateColumns.ThrottleMaxConnections = entity.ThrottleMaxConnections;
            Device newEntity = broker.Insert(updateColumns);
            return newEntity;
        }
        #endregion
    }
}
