#region License

// Copyright (c) 2011, ClearCanvas Inc.
// All rights reserved.
// http://www.clearcanvas.ca
//
// This software is licensed under the Open Software License v3.0.
// For the complete license, see http://www.clearcanvas.ca/OSLv3.0//

#endregion

// This file is auto-generated by the ClearCanvas.Model.SqlServer.CodeGenerator project.

namespace ClearCanvas.ImageServer.Model
{
    using System;
    using System.Xml;
    using ClearCanvas.Enterprise.Core;
    using ClearCanvas.ImageServer.Enterprise;
    using ClearCanvas.ImageServer.Model.EntityBrokers;

    [Serializable]
    public partial class RestoreQueue: ServerEntity
    {
        #region Constructors
        public RestoreQueue():base("RestoreQueue")
        {}
        public RestoreQueue(
             ServerEntityKey _archiveStudyStorageKey_
            ,ServerEntityKey _studyStorageKey_
            ,DateTime _scheduledTime_
            ,RestoreQueueStatusEnum _restoreQueueStatusEnum_
            ,String _processorId_
            ,String _failureDescription_
            ):base("RestoreQueue")
        {
            ArchiveStudyStorageKey = _archiveStudyStorageKey_;
            StudyStorageKey = _studyStorageKey_;
            ScheduledTime = _scheduledTime_;
            RestoreQueueStatusEnum = _restoreQueueStatusEnum_;
            ProcessorId = _processorId_;
            FailureDescription = _failureDescription_;
        }
        #endregion

        #region Public Properties
        [EntityFieldDatabaseMappingAttribute(TableName="RestoreQueue", ColumnName="ArchiveStudyStorageGUID")]
        public ServerEntityKey ArchiveStudyStorageKey
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="RestoreQueue", ColumnName="StudyStorageGUID")]
        public ServerEntityKey StudyStorageKey
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="RestoreQueue", ColumnName="ScheduledTime")]
        public DateTime ScheduledTime
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="RestoreQueue", ColumnName="RestoreQueueStatusEnum")]
        public RestoreQueueStatusEnum RestoreQueueStatusEnum
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="RestoreQueue", ColumnName="ProcessorId")]
        public String ProcessorId
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="RestoreQueue", ColumnName="FailureDescription")]
        public String FailureDescription
        { get; set; }
        #endregion

        #region Static Methods
        static public RestoreQueue Load(ServerEntityKey key)
        {
            using (var read = PersistentStoreRegistry.GetDefaultStore().OpenReadContext())
            {
                return Load(read, key);
            }
        }
        static public RestoreQueue Load(IPersistenceContext read, ServerEntityKey key)
        {
            var broker = read.GetBroker<IRestoreQueueEntityBroker>();
            RestoreQueue theObject = broker.Load(key);
            return theObject;
        }
        static public RestoreQueue Insert(RestoreQueue entity)
        {
            using (var update = PersistentStoreRegistry.GetDefaultStore().OpenUpdateContext(UpdateContextSyncMode.Flush))
            {
                RestoreQueue newEntity = Insert(update, entity);
                update.Commit();
                return newEntity;
            }
        }
        static public RestoreQueue Insert(IUpdateContext update, RestoreQueue entity)
        {
            var broker = update.GetBroker<IRestoreQueueEntityBroker>();
            var updateColumns = new RestoreQueueUpdateColumns();
            updateColumns.ArchiveStudyStorageKey = entity.ArchiveStudyStorageKey;
            updateColumns.StudyStorageKey = entity.StudyStorageKey;
            updateColumns.ScheduledTime = entity.ScheduledTime;
            updateColumns.RestoreQueueStatusEnum = entity.RestoreQueueStatusEnum;
            updateColumns.ProcessorId = entity.ProcessorId;
            updateColumns.FailureDescription = entity.FailureDescription;
            RestoreQueue newEntity = broker.Insert(updateColumns);
            return newEntity;
        }
        #endregion
    }
}
