#region License

// Copyright (c) 2009, ClearCanvas Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without modification, 
// are permitted provided that the following conditions are met:
//
//    * Redistributions of source code must retain the above copyright notice, 
//      this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above copyright notice, 
//      this list of conditions and the following disclaimer in the documentation 
//      and/or other materials provided with the distribution.
//    * Neither the name of ClearCanvas Inc. nor the names of its contributors 
//      may be used to endorse or promote products derived from this software without 
//      specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR 
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, 
// OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE 
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
// HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
// ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
// OF SUCH DAMAGE.

#endregion

// This file is auto-generated by the ClearCanvas.Model.SqlServer2005.CodeGenerator project.

namespace ClearCanvas.ImageServer.Model
{
    using System;
    using System.Xml;
    using ClearCanvas.Dicom;
    using ClearCanvas.Enterprise.Core;
    using ClearCanvas.ImageServer.Enterprise;
    using ClearCanvas.ImageServer.Model.EntityBrokers;

    [Serializable]
    public partial class StudyStorage: ServerEntity
    {
        #region Constructors
        public StudyStorage():base("StudyStorage")
        {}
        public StudyStorage(
             ServerEntityKey _serverPartitionKey_
            ,String _studyInstanceUid_
            ,DateTime _insertTime_
            ,DateTime _lastAccessedTime_
            ,Boolean _writeLock_
            ,Int16 _readLock_
            ,StudyStatusEnum _studyStatusEnum_
            ,QueueStudyStateEnum _queueStudyStateEnum_
            ):base("StudyStorage")
        {
            ServerPartitionKey = _serverPartitionKey_;
            StudyInstanceUid = _studyInstanceUid_;
            InsertTime = _insertTime_;
            LastAccessedTime = _lastAccessedTime_;
            WriteLock = _writeLock_;
            ReadLock = _readLock_;
            StudyStatusEnum = _studyStatusEnum_;
            QueueStudyStateEnum = _queueStudyStateEnum_;
        }
        #endregion

        #region Public Properties
        [EntityFieldDatabaseMappingAttribute(TableName="StudyStorage", ColumnName="ServerPartitionGUID")]
        public ServerEntityKey ServerPartitionKey
        { get; set; }
        [DicomField(DicomTags.StudyInstanceUid, DefaultValue = DicomFieldDefault.Null)]
        [EntityFieldDatabaseMappingAttribute(TableName="StudyStorage", ColumnName="StudyInstanceUid")]
        public String StudyInstanceUid
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="StudyStorage", ColumnName="InsertTime")]
        public DateTime InsertTime
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="StudyStorage", ColumnName="LastAccessedTime")]
        public DateTime LastAccessedTime
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="StudyStorage", ColumnName="WriteLock")]
        public Boolean WriteLock
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="StudyStorage", ColumnName="ReadLock")]
        public Int16 ReadLock
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="StudyStorage", ColumnName="StudyStatusEnum")]
        public StudyStatusEnum StudyStatusEnum
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="StudyStorage", ColumnName="QueueStudyStateEnum")]
        public QueueStudyStateEnum QueueStudyStateEnum
        { get; set; }
        #endregion

        #region Static Methods
        static public StudyStorage Load(ServerEntityKey key)
        {
            using (IReadContext read = PersistentStoreRegistry.GetDefaultStore().OpenReadContext())
            {
                return Load(read, key);
            }
        }
        static public StudyStorage Load(IPersistenceContext read, ServerEntityKey key)
        {
            IStudyStorageEntityBroker broker = read.GetBroker<IStudyStorageEntityBroker>();
            StudyStorage theObject = broker.Load(key);
            return theObject;
        }
        static public StudyStorage Insert(StudyStorage entity)
        {
            using (IUpdateContext update = PersistentStoreRegistry.GetDefaultStore().OpenUpdateContext(UpdateContextSyncMode.Flush))
            {
                StudyStorage newEntity = Insert(update, entity);
                update.Commit();
                return newEntity;
            }
        }
        static public StudyStorage Insert(IUpdateContext update, StudyStorage entity)
        {
            IStudyStorageEntityBroker broker = update.GetBroker<IStudyStorageEntityBroker>();
            StudyStorageUpdateColumns updateColumns = new StudyStorageUpdateColumns();
            updateColumns.ServerPartitionKey = entity.ServerPartitionKey;
            updateColumns.StudyInstanceUid = entity.StudyInstanceUid;
            updateColumns.InsertTime = entity.InsertTime;
            updateColumns.LastAccessedTime = entity.LastAccessedTime;
            updateColumns.WriteLock = entity.WriteLock;
            updateColumns.ReadLock = entity.ReadLock;
            updateColumns.StudyStatusEnum = entity.StudyStatusEnum;
            updateColumns.QueueStudyStateEnum = entity.QueueStudyStateEnum;
            StudyStorage newEntity = broker.Insert(updateColumns);
            return newEntity;
        }
        #endregion
    }
}
