#region License

// Copyright (c) 2011, ClearCanvas Inc.
// All rights reserved.
// http://www.clearcanvas.ca
//
// This software is licensed under the Open Software License v3.0.
// For the complete license, see http://www.clearcanvas.ca/OSLv3.0//

#endregion

// This file is auto-generated by the ClearCanvas.Model.SqlServer.CodeGenerator project.

namespace ClearCanvas.ImageServer.Model
{
    using System;
    using System.Xml;
    using ClearCanvas.Enterprise.Core;
    using ClearCanvas.ImageServer.Enterprise;
    using ClearCanvas.ImageServer.Model.EntityBrokers;

    [Serializable]
    public partial class StudyDataAccess: ServerEntity
    {
        #region Constructors
        public StudyDataAccess():base("StudyDataAccess")
        {}
        public StudyDataAccess(
             ServerEntityKey _studyStorageKey_
            ,ServerEntityKey _dataAccessGroupKey_
            ):base("StudyDataAccess")
        {
            StudyStorageKey = _studyStorageKey_;
            DataAccessGroupKey = _dataAccessGroupKey_;
        }
        #endregion

        #region Public Properties
        [EntityFieldDatabaseMappingAttribute(TableName="StudyDataAccess", ColumnName="StudyStorageGUID")]
        public ServerEntityKey StudyStorageKey
        { get; set; }
        [EntityFieldDatabaseMappingAttribute(TableName="StudyDataAccess", ColumnName="DataAccessGroupGUID")]
        public ServerEntityKey DataAccessGroupKey
        { get; set; }
        #endregion

        #region Static Methods
        static public StudyDataAccess Load(ServerEntityKey key)
        {
            using (IReadContext read = PersistentStoreRegistry.GetDefaultStore().OpenReadContext())
            {
                return Load(read, key);
            }
        }
        static public StudyDataAccess Load(IPersistenceContext read, ServerEntityKey key)
        {
            IStudyDataAccessEntityBroker broker = read.GetBroker<IStudyDataAccessEntityBroker>();
            StudyDataAccess theObject = broker.Load(key);
            return theObject;
        }
        static public StudyDataAccess Insert(StudyDataAccess entity)
        {
            using (IUpdateContext update = PersistentStoreRegistry.GetDefaultStore().OpenUpdateContext(UpdateContextSyncMode.Flush))
            {
                StudyDataAccess newEntity = Insert(update, entity);
                update.Commit();
                return newEntity;
            }
        }
        static public StudyDataAccess Insert(IUpdateContext update, StudyDataAccess entity)
        {
            IStudyDataAccessEntityBroker broker = update.GetBroker<IStudyDataAccessEntityBroker>();
            StudyDataAccessUpdateColumns updateColumns = new StudyDataAccessUpdateColumns();
            updateColumns.StudyStorageKey = entity.StudyStorageKey;
            updateColumns.DataAccessGroupKey = entity.DataAccessGroupKey;
            StudyDataAccess newEntity = broker.Insert(updateColumns);
            return newEntity;
        }
        #endregion
    }
}
