//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Web.View {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ImageQualitySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ImageQualitySettings defaultInstance = ((ImageQualitySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ImageQualitySettings())));
        
        public static ImageQualitySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DiagnosticDynamic")]
        public global::ClearCanvas.ImageViewer.Web.View.ImageQualityOption ImageQualityOption {
            get {
                return ((global::ClearCanvas.ImageViewer.Web.View.ImageQualityOption)(this["ImageQualityOption"]));
            }
            set {
                this["ImageQualityOption"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int JpegQualityHigh {
            get {
                return ((int)(this["JpegQualityHigh"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int JpegQualityLow {
            get {
                return ((int)(this["JpegQualityLow"]));
            }
        }
    }
}
