/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ClearCanvas.Common.Dicom {

using System;
using System.Text;
using System.Runtime.InteropServices;

public class DcmSignedShort : DcmElement {
  private HandleRef swigCPtr;

  internal DcmSignedShort(IntPtr cPtr, bool cMemoryOwn) : base(DCMTKPINVOKE.DcmSignedShortUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DcmSignedShort obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DcmSignedShort() {
    Dispose();
  }

  public override void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      DCMTKPINVOKE.delete_DcmSignedShort(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
    base.Dispose();
  }

  public DcmSignedShort(DcmTag tag, uint len) : this(DCMTKPINVOKE.new_DcmSignedShort__SWIG_0(DcmTag.getCPtr(tag), len), true) {
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public DcmSignedShort(DcmTag tag) : this(DCMTKPINVOKE.new_DcmSignedShort__SWIG_1(DcmTag.getCPtr(tag)), true) {
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public DcmSignedShort(DcmSignedShort old) : this(DCMTKPINVOKE.new_DcmSignedShort__SWIG_2(DcmSignedShort.getCPtr(old)), true) {
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override DcmEVR ident() {
    DcmEVR ret = (DcmEVR)DCMTKPINVOKE.DcmSignedShort_ident(swigCPtr);
    return ret;
  }

  public override uint getVM() {
    uint ret = DCMTKPINVOKE.DcmSignedShort_getVM(swigCPtr);
    return ret;
  }

  public override void print(SWIGTYPE_p_ostream outStream, uint flags, int level, string pixelFileName, SWIGTYPE_p_size_t pixelCounter) {
    DCMTKPINVOKE.DcmSignedShort_print__SWIG_0(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream), flags, level, pixelFileName, SWIGTYPE_p_size_t.getCPtr(pixelCounter));
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void print(SWIGTYPE_p_ostream outStream, uint flags, int level, string pixelFileName) {
    DCMTKPINVOKE.DcmSignedShort_print__SWIG_1(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream), flags, level, pixelFileName);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void print(SWIGTYPE_p_ostream outStream, uint flags, int level) {
    DCMTKPINVOKE.DcmSignedShort_print__SWIG_2(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream), flags, level);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void print(SWIGTYPE_p_ostream outStream, uint flags) {
    DCMTKPINVOKE.DcmSignedShort_print__SWIG_3(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream), flags);
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void print(SWIGTYPE_p_ostream outStream) {
    DCMTKPINVOKE.DcmSignedShort_print__SWIG_4(swigCPtr, SWIGTYPE_p_ostream.getCPtr(outStream));
    if (DCMTKPINVOKE.SWIGPendingException.Pending) throw DCMTKPINVOKE.SWIGPendingException.Retrieve();
  }

  public override OFCondition getSint16(out short sintVal, uint pos) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmSignedShort_getSint16__SWIG_0(swigCPtr, out sintVal, pos), true);
    return ret;
  }

  public override OFCondition getSint16(out short sintVal) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmSignedShort_getSint16__SWIG_1(swigCPtr, out sintVal), true);
    return ret;
  }

  public override OFCondition getSint16Array(ref IntPtr sintVals) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmSignedShort_getSint16Array(swigCPtr, ref sintVals), true);
    return ret;
  }

  public override OFCondition getOFString(StringBuilder stringVal, uint pos, bool normalize) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmSignedShort_getOFString__SWIG_0(swigCPtr, stringVal, pos, normalize), true);
    return ret;
  }

  public override OFCondition getOFString(StringBuilder stringVal, uint pos) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmSignedShort_getOFString__SWIG_1(swigCPtr, stringVal, pos), true);
    return ret;
  }

  public override OFCondition putSint16(short sintVal, uint pos) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmSignedShort_putSint16__SWIG_0(swigCPtr, sintVal, pos), true);
    return ret;
  }

  public override OFCondition putSint16(short sintVal) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmSignedShort_putSint16__SWIG_1(swigCPtr, sintVal), true);
    return ret;
  }

  public override OFCondition putSint16Array(short[] sintVals, uint numSints) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmSignedShort_putSint16Array(swigCPtr, sintVals, numSints), true);
    return ret;
  }

  public override OFCondition putString(string stringVal) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmSignedShort_putString(swigCPtr, stringVal), true);
    return ret;
  }

  public override OFCondition verify(bool autocorrect) {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmSignedShort_verify__SWIG_0(swigCPtr, autocorrect), true);
    return ret;
  }

  public override OFCondition verify() {
    OFCondition ret = new OFCondition(DCMTKPINVOKE.DcmSignedShort_verify__SWIG_1(swigCPtr), true);
    return ret;
  }

}

}
