/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ClearCanvas.Common.Dicom {

using System;
using System.Text;
using System.Runtime.InteropServices;

public class LST_HEAD : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LST_HEAD(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(LST_HEAD obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~LST_HEAD() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      DCMTKPINVOKE.delete_LST_HEAD(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public LST_HEAD() : this(DCMTKPINVOKE.new_LST_HEAD(), true) {
  }

  public void push_back(SWIGTYPE_p_void node) {
    DCMTKPINVOKE.LST_HEAD_push_back(swigCPtr, SWIGTYPE_p_void.getCPtr(node));
  }

  public SWIGTYPE_p_void dequeue() {
    IntPtr cPtr = DCMTKPINVOKE.LST_HEAD_dequeue(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public uint size() {
    uint ret = DCMTKPINVOKE.LST_HEAD_size(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_void front() {
    IntPtr cPtr = DCMTKPINVOKE.LST_HEAD_front(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_void position(SWIGTYPE_p_void node) {
    IntPtr cPtr = DCMTKPINVOKE.LST_HEAD_position(swigCPtr, SWIGTYPE_p_void.getCPtr(node));
    SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_void next() {
    IntPtr cPtr = DCMTKPINVOKE.LST_HEAD_next(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_void current() {
    IntPtr cPtr = DCMTKPINVOKE.LST_HEAD_current(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

}

}
