/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace ClearCanvas.Common.Dicom {

public enum T_DIMSE_Priority {
  DIMSE_PRIORITY_LOW = 0x0002,
  DIMSE_PRIORITY_MEDIUM = 0x0000,
  DIMSE_PRIORITY_HIGH = 0x0001
}

}
