//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Shreds.Configuration {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Shreds.Configuration.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Server.
        /// </summary>
        internal static string DicomServerConfiguration {
            get {
                return ResourceManager.GetString("DicomServerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diskspace Manager.
        /// </summary>
        internal static string DiskspaceManagerConfiguration {
            get {
                return ResourceManager.GetString("DiskspaceManagerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the Dicom Server configuration.  Please ensure the service is running and try again..
        /// </summary>
        internal static string ExceptionDicomServerConfigurationRefreshFailed {
            get {
                return ResourceManager.GetString("ExceptionDicomServerConfigurationRefreshFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the Dicom Server configuration.  Please ensure the service is running and try again..
        /// </summary>
        internal static string ExceptionDicomServerConfigurationUpdateFailed {
            get {
                return ResourceManager.GetString("ExceptionDicomServerConfigurationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        internal static string LabelBytes {
            get {
                return ResourceManager.GetString("LabelBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string LabelGigabytes {
            get {
                return ResourceManager.GetString("LabelGigabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string LabelKilobytes {
            get {
                return ResourceManager.GetString("LabelKilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string LabelMegabytes {
            get {
                return ResourceManager.GetString("LabelMegabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string LabelTerabytes {
            get {
                return ResourceManager.GetString("LabelTerabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve Diskspace Management settings.  Make sure the ClearCanvas Service is running..
        /// </summary>
        internal static string MessageFailedToRetrieveDiskspaceManagementSettings {
            get {
                return ResourceManager.GetString("MessageFailedToRetrieveDiskspaceManagementSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update Diskspace Management settings.  Make sure the ClearCanvas Service is running..
        /// </summary>
        internal static string MessageFailedToUpdateDiskspaceManagementSettings {
            get {
                return ResourceManager.GetString("MessageFailedToUpdateDiskspaceManagementSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AE Title contains invalid characters..
        /// </summary>
        internal static string ValidationAETitleInvalidCharacters {
            get {
                return ResourceManager.GetString("ValidationAETitleInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AE Title must be between 1 and 16 characters..
        /// </summary>
        internal static string ValidationAETitleLengthIncorrect {
            get {
                return ResourceManager.GetString("ValidationAETitleLengthIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Port must be between 1 and 65535..
        /// </summary>
        internal static string ValidationPortOutOfRange {
            get {
                return ResourceManager.GetString("ValidationPortOutOfRange", resourceCulture);
            }
        }
    }
}
