USE [master]
CREATE DATABASE [Enterprise1] ON  PRIMARY ( NAME = N'Enterprise1', FILENAME = N'D:\sqldb\Enterprise1.mdf' , SIZE = 30720KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ) LOG ON ( NAME = N'Enterprise1_log', FILENAME = N'D:\sqldb\Enterprise1_log.ldf' , SIZE = 22144KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
EXEC dbo.sp_dbcmptlevel @dbname=N'Enterprise1', @new_cmptlevel=90
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled')) begin EXEC [Enterprise1].[dbo].[sp_fulltext_database] @action = 'enable' end
ALTER DATABASE [Enterprise1] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [Enterprise1] SET ANSI_NULLS OFF 
ALTER DATABASE [Enterprise1] SET ANSI_PADDING OFF 
ALTER DATABASE [Enterprise1] SET ANSI_WARNINGS OFF 
ALTER DATABASE [Enterprise1] SET ARITHABORT OFF 
ALTER DATABASE [Enterprise1] SET AUTO_CLOSE OFF 
ALTER DATABASE [Enterprise1] SET AUTO_CREATE_STATISTICS ON 
ALTER DATABASE [Enterprise1] SET AUTO_SHRINK OFF 
ALTER DATABASE [Enterprise1] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [Enterprise1] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [Enterprise1] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [Enterprise1] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [Enterprise1] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [Enterprise1] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [Enterprise1] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [Enterprise1] SET  DISABLE_BROKER 
ALTER DATABASE [Enterprise1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [Enterprise1] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [Enterprise1] SET TRUSTWORTHY OFF 
ALTER DATABASE [Enterprise1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
ALTER DATABASE [Enterprise1] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [Enterprise1] SET  READ_WRITE 
ALTER DATABASE [Enterprise1] SET RECOVERY SIMPLE 
ALTER DATABASE [Enterprise1] SET  MULTI_USER 
ALTER DATABASE [Enterprise1] SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE [Enterprise1] SET DB_CHAINING OFF 