//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Enterprise.Desktop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Enterprise.Desktop.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ColumnActive {
            get {
                return ResourceManager.GetString("ColumnActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority Group.
        /// </summary>
        internal static string ColumnAuthorityGroup {
            get {
                return ResourceManager.GetString("ColumnAuthorityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnAuthorityGroupName {
            get {
                return ResourceManager.GetString("ColumnAuthorityGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ColumnAuthorityTokenDescription {
            get {
                return ResourceManager.GetString("ColumnAuthorityTokenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnAuthorityTokenName {
            get {
                return ResourceManager.GetString("ColumnAuthorityTokenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string ColumnUser {
            get {
                return ResourceManager.GetString("ColumnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string ColumnUserId {
            get {
                return ResourceManager.GetString("ColumnUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnUserName {
            get {
                return ResourceManager.GetString("ColumnUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save Authority Group.
        /// </summary>
        internal static string ExceptionSaveAuthorityGroup {
            get {
                return ResourceManager.GetString("ExceptionSaveAuthorityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save User.
        /// </summary>
        internal static string ExceptionSaveUser {
            get {
                return ResourceManager.GetString("ExceptionSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected item(s)?.
        /// </summary>
        internal static string MessageConfirmDeleteSelectedItems {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Authority Group.
        /// </summary>
        internal static string TitleAddAuthorityGroup {
            get {
                return ResourceManager.GetString("TitleAddAuthorityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string TitleAddUser {
            get {
                return ResourceManager.GetString("TitleAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority Group Admin.
        /// </summary>
        internal static string TitleAuthorityGroup {
            get {
                return ResourceManager.GetString("TitleAuthorityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string TitleResetPassword {
            get {
                return ResourceManager.GetString("TitleResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Authority Group.
        /// </summary>
        internal static string TitleUpdateAuthorityGroup {
            get {
                return ResourceManager.GetString("TitleUpdateAuthorityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User.
        /// </summary>
        internal static string TitleUpdateUser {
            get {
                return ResourceManager.GetString("TitleUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Admin.
        /// </summary>
        internal static string TitleUser {
            get {
                return ResourceManager.GetString("TitleUser", resourceCulture);
            }
        }
    }
}
