tlist.o: tlist.cxx ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofstream.h ../include/oflist.h \
  ../include/oftypes.h ../include/ofcast.h ../include/ofstdinc.h \
  ../include/ofalgo.h ../include/ofconsol.h ../include/ofthread.h \
  ../include/ofstring.h
tofdatim.o: tofdatim.cxx ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofdate.h ../include/ofstring.h \
  ../include/oftypes.h ../include/ofcast.h ../include/ofstdinc.h \
  ../include/ofstream.h ../include/oftime.h ../include/ofdatime.h \
  ../include/ofconsol.h ../include/ofthread.h
tofstd.o: tofstd.cxx ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofstd.h ../include/oflist.h \
  ../include/oftypes.h ../include/ofcast.h ../include/ofstdinc.h \
  ../include/ofstring.h ../include/ofstream.h ../include/ofconsol.h \
  ../include/ofthread.h
tstatof.o: tstatof.cxx ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofstd.h ../include/oflist.h \
  ../include/oftypes.h ../include/ofcast.h ../include/ofstdinc.h \
  ../include/ofstring.h ../include/ofstream.h ../include/ofconsol.h \
  ../include/ofthread.h
tstftoa.o: tstftoa.cxx ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofstd.h ../include/oflist.h \
  ../include/oftypes.h ../include/ofcast.h ../include/ofstdinc.h \
  ../include/ofstring.h ../include/ofstream.h ../include/ofconsol.h \
  ../include/ofthread.h
tstlist.o: tstlist.cxx ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofstream.h ../include/ofalgo.h \
  ../include/oftypes.h ../include/oflist.h ../include/ofcast.h \
  ../include/ofstdinc.h ../include/ofconsol.h ../include/ofthread.h \
  ../include/ofstring.h
tstring.o: tstring.cxx ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofstring.h \
  ../include/oftypes.h ../include/ofcast.h ../include/ofstdinc.h \
  ../include/ofstream.h ../include/ofconsol.h ../include/ofthread.h \
  ../include/ofstd.h ../include/oflist.h
tststack.o: tststack.cxx ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofstream.h \
  ../include/ofstack.h ../include/oftypes.h ../include/ofcast.h \
  ../include/ofstdinc.h ../include/ofconsol.h ../include/ofthread.h \
  ../include/ofstring.h
tstthred.o: tstthred.cxx ../../config/include/osconfig.h \
  ../../config/include/cfunix.h ../include/ofconsol.h \
  ../include/ofstream.h ../include/ofthread.h ../include/oftypes.h \
  ../include/ofstring.h ../include/ofcast.h ../include/ofstdinc.h \
  ../include/ofstd.h ../include/oflist.h
