//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Services.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Services.Tools.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Inactive.
        /// </summary>
        internal static string ClearInactive {
            get {
                return ResourceManager.GetString("ClearInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selected.
        /// </summary>
        internal static string ClearSelected {
            get {
                return ResourceManager.GetString("ClearSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifiers must match..
        /// </summary>
        internal static string ExceptionIdentifiersMustMatch {
            get {
                return ResourceManager.GetString("ExceptionIdentifiersMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        internal static string FormatXDaysAgo {
            get {
                return ResourceManager.GetString("FormatXDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours, .
        /// </summary>
        internal static string FormatXHoursAgo {
            get {
                return ResourceManager.GetString("FormatXHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        internal static string FormatXMinutesAgo {
            get {
                return ResourceManager.GetString("FormatXMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ImportDicomFiles {
            get {
                return ResourceManager.GetString("ImportDicomFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MenuCancel {
            get {
                return ResourceManager.GetString("MenuCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string MenuClear {
            get {
                return ResourceManager.GetString("MenuClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MenuDeleteStudy {
            get {
                return ResourceManager.GetString("MenuDeleteStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Activity Monitor.
        /// </summary>
        internal static string MenuDicomFileImportActivity {
            get {
                return ResourceManager.GetString("MenuDicomFileImportActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send/Receive Activity Monitor.
        /// </summary>
        internal static string MenuDicomSendReceiveActivity {
            get {
                return ResourceManager.GetString("MenuDicomSendReceiveActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reindex Local Data Store.
        /// </summary>
        internal static string MenuLocalDataStoreReindex {
            get {
                return ResourceManager.GetString("MenuLocalDataStoreReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MenuOpenStudies {
            get {
                return ResourceManager.GetString("MenuOpenStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string MenuRestart {
            get {
                return ResourceManager.GetString("MenuRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        internal static string MenuRetrieveStudy {
            get {
                return ResourceManager.GetString("MenuRetrieveStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string MenuSendStudy {
            get {
                return ResourceManager.GetString("MenuSendStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string MenuServices {
            get {
                return ResourceManager.GetString("MenuServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string MenuStart {
            get {
                return ResourceManager.GetString("MenuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string MenuStop {
            get {
                return ResourceManager.GetString("MenuStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Activity Monitor service is currently unavailable.
        /// </summary>
        internal static string MessageActivityMonitorServiceUnavailable {
            get {
                return ResourceManager.GetString("MessageActivityMonitorServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cancel the selected items..
        /// </summary>
        internal static string MessageCancelFailed {
            get {
                return ResourceManager.GetString("MessageCancelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clear the selected items..
        /// </summary>
        internal static string MessageClearFailed {
            get {
                return ResourceManager.GetString("MessageClearFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clear the selected items..
        /// </summary>
        internal static string MessageClearInactiveFailed {
            get {
                return ResourceManager.GetString("MessageClearInactiveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling a reindex operation will cause your data store to be out of sync with the files stored on your local machine.
        ///Do you want to cancel the reindex operation anyway?.
        /// </summary>
        internal static string MessageConfirmCancelReindex {
            get {
                return ResourceManager.GetString("MessageConfirmCancelReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the {0} selected studies?.
        /// </summary>
        internal static string MessageConfirmDeleteStudies {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected study?.
        /// </summary>
        internal static string MessageConfirmDeleteStudy {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected multiple servers to send to.  Are you sure you want to continue?.
        /// </summary>
        internal static string MessageConfirmSendToMultipleServers {
            get {
                return ResourceManager.GetString("MessageConfirmSendToMultipleServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting studies ....
        /// </summary>
        internal static string MessageDeletingStudies {
            get {
                return ResourceManager.GetString("MessageDeletingStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion progress can no longer be obtained; the connection to the required service has been lost..
        /// </summary>
        internal static string MessageDeletionHelperConnectionLost {
            get {
                return ResourceManager.GetString("MessageDeletionHelperConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process delete request because the Local Data Store service is not running.
        ///Please ensure the ClearCanvas server is running or contact your system administrator for assistance..
        /// </summary>
        internal static string MessageDeletionHelperUnableToConnect {
            get {
                return ResourceManager.GetString("MessageDeletionHelperUnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initiate an import of the selected items..
        /// </summary>
        internal static string MessageFailedToImportSelection {
            get {
                return ResourceManager.GetString("MessageFailedToImportSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch the Import Activity manager, likely due to a communication error with the service.  Please check and make sure the service is running or call your system administrator..
        /// </summary>
        internal static string MessageFailedToLaunchImportActivityComponent {
            get {
                return ResourceManager.GetString("MessageFailedToLaunchImportActivityComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch the Reindex Activity manager, likely due to a communication error with the Failed to launch the Import Activity manager, likely due to a communication error with the service.  Please check and make sure the service is running or call your system administrator..
        /// </summary>
        internal static string MessageFailedToLaunchReindexComponent {
            get {
                return ResourceManager.GetString("MessageFailedToLaunchReindexComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch the Send/Receive Activity manager, likely due to a communication error with the service.  Please check and make sure the service is running or call your system administrator..
        /// </summary>
        internal static string MessageFailedToLaunchSendReceiveActivityComponent {
            get {
                return ResourceManager.GetString("MessageFailedToLaunchSendReceiveActivityComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restart service. Please check the logs for more details..
        /// </summary>
        internal static string MessageFailedToRestartService {
            get {
                return ResourceManager.GetString("MessageFailedToRestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initiate a retrieval of the selected items..
        /// </summary>
        internal static string MessageFailedToRetrieveStudy {
            get {
                return ResourceManager.GetString("MessageFailedToRetrieveStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initiate sending of the selected items..
        /// </summary>
        internal static string MessageFailedToSendStudy {
            get {
                return ResourceManager.GetString("MessageFailedToSendStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start delete operation, possibly because a conflicting operation is currently running.  If this problem persists, please contact your system administrator..
        /// </summary>
        internal static string MessageFailedToStartDelete {
            get {
                return ResourceManager.GetString("MessageFailedToStartDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start reindex operation, possibly because a conflicting operation is currently running.  If this problem persists, please contact your system administrator..
        /// </summary>
        internal static string MessageFailedToStartReindex {
            get {
                return ResourceManager.GetString("MessageFailedToStartReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service. Please check the logs for more details..
        /// </summary>
        internal static string MessageFailedToStartService {
            get {
                return ResourceManager.GetString("MessageFailedToStartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop service. Please check the logs for more details..
        /// </summary>
        internal static string MessageFailedToStopService {
            get {
                return ResourceManager.GetString("MessageFailedToStopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import the selected items because the Local Data Store service is not running.
        ///Please ensure the ClearCanvas server is running or contact your system administrator for assistance..
        /// </summary>
        internal static string MessageImportLocalDataStoreServiceNotRunning {
            get {
                return ResourceManager.GetString("MessageImportLocalDataStoreServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing has been selected..
        /// </summary>
        internal static string MessageNothingSelected {
            get {
                return ResourceManager.GetString("MessageNothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day ago.
        /// </summary>
        internal static string MessageOneDayAgo {
            get {
                return ResourceManager.GetString("MessageOneDayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour, .
        /// </summary>
        internal static string MessageOneHourAgo {
            get {
                return ResourceManager.GetString("MessageOneHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute ago.
        /// </summary>
        internal static string MessageOneMinuteAgo {
            get {
                return ResourceManager.GetString("MessageOneMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the selected studies is in use.  Please close all relevant workspaces before deleting..
        /// </summary>
        internal static string MessageOneOfSelectedStudiesInUse {
            get {
                return ResourceManager.GetString("MessageOneOfSelectedStudiesInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reindex the Local Data Store because the Local Data Store service is not running.
        ///Please ensure the ClearCanvas server is running or contact your system administrator for assistance..
        /// </summary>
        internal static string MessageReindexLocalDataStoreServiceNotRunning {
            get {
                return ResourceManager.GetString("MessageReindexLocalDataStoreServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the selected studies because the Dicom Server service is not running.
        ///Please ensure the ClearCanvas server is running or contact your system administrator for assistance..
        /// </summary>
        internal static string MessageRetrieveDicomServerServiceNotRunning {
            get {
                return ResourceManager.GetString("MessageRetrieveDicomServerServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a destination..
        /// </summary>
        internal static string MessageSelectDestination {
            get {
                return ResourceManager.GetString("MessageSelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected study is currently in use.  Please close all relevant workspaces before deleting..
        /// </summary>
        internal static string MessageSelectedStudyInUse {
            get {
                return ResourceManager.GetString("MessageSelectedStudyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send the selected studies because the Dicom Server service is not running.
        ///Please ensure the ClearCanvas server is running or contact your system administrator for assistance..
        /// </summary>
        internal static string MessageSendDicomServerServiceNotRunning {
            get {
                return ResourceManager.GetString("MessageSendDicomServerServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of the selected studies are in use.  Please close all relevant workspaces before deleting..
        /// </summary>
        internal static string MessageSomeOfSelectedStudiesInUse {
            get {
                return ResourceManager.GetString("MessageSomeOfSelectedStudiesInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string TitleAvailable {
            get {
                return ResourceManager.GetString("TitleAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TitleDescription {
            get {
                return ResourceManager.GetString("TitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string TitleFailed {
            get {
                return ResourceManager.GetString("TitleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string TitleFrom {
            get {
                return ResourceManager.GetString("TitleFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Activity.
        /// </summary>
        internal static string TitleImportActivity {
            get {
                return ResourceManager.GetString("TitleImportActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Active.
        /// </summary>
        internal static string TitleLastActive {
            get {
                return ResourceManager.GetString("TitleLastActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string TitleMessage {
            get {
                return ResourceManager.GetString("TitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Id.
        /// </summary>
        internal static string TitlePatientId {
            get {
                return ResourceManager.GetString("TitlePatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient&apos;s Name.
        /// </summary>
        internal static string TitlePatientsName {
            get {
                return ResourceManager.GetString("TitlePatientsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        internal static string TitleReceive {
            get {
                return ResourceManager.GetString("TitleReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string TitleReceived {
            get {
                return ResourceManager.GetString("TitleReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reindex Local Data Store.
        /// </summary>
        internal static string TitleReindexLocalDataStore {
            get {
                return ResourceManager.GetString("TitleReindexLocalDataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string TitleSend {
            get {
                return ResourceManager.GetString("TitleSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Study.
        /// </summary>
        internal static string TitleSendStudy {
            get {
                return ResourceManager.GetString("TitleSendStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string TitleSent {
            get {
                return ResourceManager.GetString("TitleSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string TitleStartTime {
            get {
                return ResourceManager.GetString("TitleStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string TitleStatus {
            get {
                return ResourceManager.GetString("TitleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Date.
        /// </summary>
        internal static string TitleStudyDate {
            get {
                return ResourceManager.GetString("TitleStudyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Description.
        /// </summary>
        internal static string TitleStudyDescription {
            get {
                return ResourceManager.GetString("TitleStudyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string TitleTo {
            get {
                return ResourceManager.GetString("TitleTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ToolbarDeleteStudy {
            get {
                return ResourceManager.GetString("ToolbarDeleteStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ToolbarOpenStudies {
            get {
                return ResourceManager.GetString("ToolbarOpenStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        internal static string ToolbarRetrieveStudy {
            get {
                return ResourceManager.GetString("ToolbarRetrieveStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string ToolbarSendStudy {
            get {
                return ResourceManager.GetString("ToolbarSendStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TooltipCancel {
            get {
                return ResourceManager.GetString("TooltipCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string TooltipClear {
            get {
                return ResourceManager.GetString("TooltipClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Items.
        /// </summary>
        internal static string TooltipClearAll {
            get {
                return ResourceManager.GetString("TooltipClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Inactive.
        /// </summary>
        internal static string TooltipClearInactive {
            get {
                return ResourceManager.GetString("TooltipClearInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selected Item(s).
        /// </summary>
        internal static string TooltipClearSelected {
            get {
                return ResourceManager.GetString("TooltipClearSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete study.
        /// </summary>
        internal static string TooltipDeleteStudy {
            get {
                return ResourceManager.GetString("TooltipDeleteStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import dicom files from the local file system.
        /// </summary>
        internal static string TooltipImportDicomFiles {
            get {
                return ResourceManager.GetString("TooltipImportDicomFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string TooltipOpenStudies {
            get {
                return ResourceManager.GetString("TooltipOpenStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Study.
        /// </summary>
        internal static string TooltipRetrieveStudy {
            get {
                return ResourceManager.GetString("TooltipRetrieveStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Study.
        /// </summary>
        internal static string TooltipSendStudy {
            get {
                return ResourceManager.GetString("TooltipSendStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Background Imports.
        /// </summary>
        internal static string TooltipShowBackgroundImports {
            get {
                return ResourceManager.GetString("TooltipShowBackgroundImports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Background Sends.
        /// </summary>
        internal static string TooltipShowBackgroundSends {
            get {
                return ResourceManager.GetString("TooltipShowBackgroundSends", resourceCulture);
            }
        }
    }
}
