//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Ris.Client.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Ris.Client.Admin.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ColumnActive {
            get {
                return ResourceManager.GetString("ColumnActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed.
        /// </summary>
        internal static string ColumnBed {
            get {
                return ResourceManager.GetString("ColumnBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string ColumnBuilding {
            get {
                return ResourceManager.GetString("ColumnBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string ColumnCategory {
            get {
                return ResourceManager.GetString("ColumnCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string ColumnCode {
            get {
                return ResourceManager.GetString("ColumnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        internal static string ColumnDegree {
            get {
                return ResourceManager.GetString("ColumnDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ColumnDescription {
            get {
                return ResourceManager.GetString("ColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility.
        /// </summary>
        internal static string ColumnFacility {
            get {
                return ResourceManager.GetString("ColumnFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Name.
        /// </summary>
        internal static string ColumnFamilyName {
            get {
                return ResourceManager.GetString("ColumnFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string ColumnFloor {
            get {
                return ResourceManager.GetString("ColumnFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Name.
        /// </summary>
        internal static string ColumnGivenName {
            get {
                return ResourceManager.GetString("ColumnGivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ColumnID {
            get {
                return ResourceManager.GetString("ColumnID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Date.
        /// </summary>
        internal static string ColumnInactiveDate {
            get {
                return ResourceManager.GetString("ColumnInactiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LicenseNumber.
        /// </summary>
        internal static string ColumnLicenseNumber {
            get {
                return ResourceManager.GetString("ColumnLicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string ColumnMiddleName {
            get {
                return ResourceManager.GetString("ColumnMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Of Care.
        /// </summary>
        internal static string ColumnPointOfCare {
            get {
                return ResourceManager.GetString("ColumnPointOfCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string ColumnPrefix {
            get {
                return ResourceManager.GetString("ColumnPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string ColumnRoom {
            get {
                return ResourceManager.GetString("ColumnRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string ColumnSeverity {
            get {
                return ResourceManager.GetString("ColumnSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        internal static string ColumnSuffix {
            get {
                return ResourceManager.GetString("ColumnSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagnostic service was modified by another user.  Your changes could not be saved..
        /// </summary>
        internal static string ExceptionConcurrencyDiagnosticServiceNotSaved {
            get {
                return ResourceManager.GetString("ExceptionConcurrencyDiagnosticServiceNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The facility was modified by another user.  Your changes could not be saved..
        /// </summary>
        internal static string ExceptionConcurrencyFacilityNotSaved {
            get {
                return ResourceManager.GetString("ExceptionConcurrencyFacilityNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location was modified by another user.  Your changes could not be saved..
        /// </summary>
        internal static string ExceptionConcurrencyLocationNotSaved {
            get {
                return ResourceManager.GetString("ExceptionConcurrencyLocationNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The modality was modified by another user.  Your changes could not be saved..
        /// </summary>
        internal static string ExceptionConcurrencyModalityNotSaved {
            get {
                return ResourceManager.GetString("ExceptionConcurrencyModalityNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The practitioner was modified by another user.  Your changes could not be saved..
        /// </summary>
        internal static string ExceptionConcurrencyPractitionerNotSaved {
            get {
                return ResourceManager.GetString("ExceptionConcurrencyPractitionerNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The staff was modified by another user.  Your changes could not be saved..
        /// </summary>
        internal static string ExceptionConcurrencyStaffNotSaved {
            get {
                return ResourceManager.GetString("ExceptionConcurrencyStaffNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while attempting to save changes to this item.
        /// </summary>
        internal static string ExceptionFailedToSave {
            get {
                return ResourceManager.GetString("ExceptionFailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string LabelEdit {
            get {
                return ResourceManager.GetString("LabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string LabelReset {
            get {
                return ResourceManager.GetString("LabelReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        internal static string LabelResetAll {
            get {
                return ResourceManager.GetString("LabelResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        internal static string LabelSaveAll {
            get {
                return ResourceManager.GetString("LabelSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this diagnostic service?.
        /// </summary>
        internal static string MessageDeleteSelectedDiagnosticService {
            get {
                return ResourceManager.GetString("MessageDeleteSelectedDiagnosticService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this facility?.
        /// </summary>
        internal static string MessageDeleteSelectedFacility {
            get {
                return ResourceManager.GetString("MessageDeleteSelectedFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this location?.
        /// </summary>
        internal static string MessageDeleteSelectedLocation {
            get {
                return ResourceManager.GetString("MessageDeleteSelectedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this modality?.
        /// </summary>
        internal static string MessageDeleteSelectedModality {
            get {
                return ResourceManager.GetString("MessageDeleteSelectedModality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this staff?.
        /// </summary>
        internal static string MessageDeleteSelectedStaff {
            get {
                return ResourceManager.GetString("MessageDeleteSelectedStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This diagnostic ID already exist.  Your changes could not be saved..
        /// </summary>
        internal static string MessageDuplicateDiagnosticServiceID {
            get {
                return ResourceManager.GetString("MessageDuplicateDiagnosticServiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This modality ID already exist.  Your changes could not be saved..
        /// </summary>
        internal static string MessageDuplicateModalityID {
            get {
                return ResourceManager.GetString("MessageDuplicateModalityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Diagnostic Service ....
        /// </summary>
        internal static string TitleAddDiagnosticService {
            get {
                return ResourceManager.GetString("TitleAddDiagnosticService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Facility.
        /// </summary>
        internal static string TitleAddFacility {
            get {
                return ResourceManager.GetString("TitleAddFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location.
        /// </summary>
        internal static string TitleAddLocation {
            get {
                return ResourceManager.GetString("TitleAddLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Modality.
        /// </summary>
        internal static string TitleAddModality {
            get {
                return ResourceManager.GetString("TitleAddModality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note Category.
        /// </summary>
        internal static string TitleAddNoteCategory {
            get {
                return ResourceManager.GetString("TitleAddNoteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Practitioner.
        /// </summary>
        internal static string TitleAddPractitioner {
            get {
                return ResourceManager.GetString("TitleAddPractitioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Staff.
        /// </summary>
        internal static string TitleAddStaff {
            get {
                return ResourceManager.GetString("TitleAddStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Diagnostic Service.
        /// </summary>
        internal static string TitleDeleteDiagnosticService {
            get {
                return ResourceManager.GetString("TitleDeleteDiagnosticService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Facility.
        /// </summary>
        internal static string TitleDeleteFacility {
            get {
                return ResourceManager.GetString("TitleDeleteFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Location.
        /// </summary>
        internal static string TitleDeleteLocation {
            get {
                return ResourceManager.GetString("TitleDeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Modality.
        /// </summary>
        internal static string TitleDeleteModality {
            get {
                return ResourceManager.GetString("TitleDeleteModality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Practitioner.
        /// </summary>
        internal static string TitleDeletePractitioner {
            get {
                return ResourceManager.GetString("TitleDeletePractitioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Staff.
        /// </summary>
        internal static string TitleDeleteStaff {
            get {
                return ResourceManager.GetString("TitleDeleteStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic Services.
        /// </summary>
        internal static string TitleDiagnosticServices {
            get {
                return ResourceManager.GetString("TitleDiagnosticServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities.
        /// </summary>
        internal static string TitleFacilities {
            get {
                return ResourceManager.GetString("TitleFacilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Diagnostic Services.
        /// </summary>
        internal static string TitleImportDiagnosticServices {
            get {
                return ResourceManager.GetString("TitleImportDiagnosticServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string TitleLocations {
            get {
                return ResourceManager.GetString("TitleLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalities.
        /// </summary>
        internal static string TitleModalities {
            get {
                return ResourceManager.GetString("TitleModalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Categories.
        /// </summary>
        internal static string TitleNoteCategories {
            get {
                return ResourceManager.GetString("TitleNoteCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practitioner.
        /// </summary>
        internal static string TitlePractitioner {
            get {
                return ResourceManager.GetString("TitlePractitioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string TitleStaff {
            get {
                return ResourceManager.GetString("TitleStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Diagnostic Service ....
        /// </summary>
        internal static string TitleUpdateDiagnosticService {
            get {
                return ResourceManager.GetString("TitleUpdateDiagnosticService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Facility.
        /// </summary>
        internal static string TitleUpdateFacility {
            get {
                return ResourceManager.GetString("TitleUpdateFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Location.
        /// </summary>
        internal static string TitleUpdateLocation {
            get {
                return ResourceManager.GetString("TitleUpdateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Modality.
        /// </summary>
        internal static string TitleUpdateModality {
            get {
                return ResourceManager.GetString("TitleUpdateModality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Note Category.
        /// </summary>
        internal static string TitleUpdateNoteCategory {
            get {
                return ResourceManager.GetString("TitleUpdateNoteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Practitioner.
        /// </summary>
        internal static string TitleUpdatePractitioner {
            get {
                return ResourceManager.GetString("TitleUpdatePractitioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Staff.
        /// </summary>
        internal static string TitleUpdateStaff {
            get {
                return ResourceManager.GetString("TitleUpdateStaff", resourceCulture);
            }
        }
    }
}
