USE [master]
CREATE DATABASE [++DB++] ON  PRIMARY ( NAME = N'++DB++', FILENAME = N'++DBFOLDER++\++DB++.mdf' , SIZE = 30720KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ) LOG ON ( NAME = N'++DB++_log', FILENAME = N'++LOGFOLDER++\++DB++_log.ldf' , SIZE = 22144KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
EXEC dbo.sp_dbcmptlevel @dbname=N'++DB++', @new_cmptlevel=90
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled')) begin EXEC [++DB++].[dbo].[sp_fulltext_database] @action = 'enable' end
ALTER DATABASE [++DB++] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [++DB++] SET ANSI_NULLS OFF 
ALTER DATABASE [++DB++] SET ANSI_PADDING OFF 
ALTER DATABASE [++DB++] SET ANSI_WARNINGS OFF 
ALTER DATABASE [++DB++] SET ARITHABORT OFF 
ALTER DATABASE [++DB++] SET AUTO_CLOSE OFF 
ALTER DATABASE [++DB++] SET AUTO_CREATE_STATISTICS ON 
ALTER DATABASE [++DB++] SET AUTO_SHRINK OFF 
ALTER DATABASE [++DB++] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [++DB++] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [++DB++] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [++DB++] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [++DB++] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [++DB++] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [++DB++] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [++DB++] SET  DISABLE_BROKER 
ALTER DATABASE [++DB++] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [++DB++] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [++DB++] SET TRUSTWORTHY OFF 
ALTER DATABASE [++DB++] SET ALLOW_SNAPSHOT_ISOLATION OFF 
ALTER DATABASE [++DB++] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [++DB++] SET  READ_WRITE 
ALTER DATABASE [++DB++] SET RECOVERY SIMPLE 
ALTER DATABASE [++DB++] SET  MULTI_USER 
ALTER DATABASE [++DB++] SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE [++DB++] SET DB_CHAINING OFF 