#region License

// Copyright (c) 2006-2009, ClearCanvas Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without modification, 
// are permitted provided that the following conditions are met:
//
//    * Redistributions of source code must retain the above copyright notice, 
//      this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above copyright notice, 
//      this list of conditions and the following disclaimer in the documentation 
//      and/or other materials provided with the distribution.
//    * Neither the name of ClearCanvas Inc. nor the names of its contributors 
//      may be used to endorse or promote products derived from this software without 
//      specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR 
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, 
// OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE 
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
// HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
// ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
// OF SUCH DAMAGE.

#endregion

// This file is auto-generated by the ClearCanvas.Model.SqlServer2005.CodeGenerator project.

namespace ClearCanvas.ImageServer.Model.EntityBrokers
{
    using ClearCanvas.Enterprise.Core;
    using ClearCanvas.ImageServer.Enterprise;

    public partial class SeriesSelectCriteria : EntitySelectCriteria
    {
        public SeriesSelectCriteria()
        : base("Series")
        {}
        [EntityFieldDatabaseMappingAttribute(TableName="Series", ColumnName="Modality")]
        public ISearchCondition<System.String> Modality
        {
            get
            {
              if (!SubCriteria.ContainsKey("Modality"))
              {
                 SubCriteria["Modality"] = new SearchCondition<System.String>("Modality");
              }
              return (ISearchCondition<System.String>)SubCriteria["Modality"];
            } 
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Series", ColumnName="NumberOfSeriesRelatedInstances")]
        public ISearchCondition<System.Int32> NumberOfSeriesRelatedInstances
        {
            get
            {
              if (!SubCriteria.ContainsKey("NumberOfSeriesRelatedInstances"))
              {
                 SubCriteria["NumberOfSeriesRelatedInstances"] = new SearchCondition<System.Int32>("NumberOfSeriesRelatedInstances");
              }
              return (ISearchCondition<System.Int32>)SubCriteria["NumberOfSeriesRelatedInstances"];
            } 
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Series", ColumnName="PerformedProcedureStepStartDate")]
        public ISearchCondition<System.String> PerformedProcedureStepStartDate
        {
            get
            {
              if (!SubCriteria.ContainsKey("PerformedProcedureStepStartDate"))
              {
                 SubCriteria["PerformedProcedureStepStartDate"] = new SearchCondition<System.String>("PerformedProcedureStepStartDate");
              }
              return (ISearchCondition<System.String>)SubCriteria["PerformedProcedureStepStartDate"];
            } 
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Series", ColumnName="PerformedProcedureStepStartTime")]
        public ISearchCondition<System.String> PerformedProcedureStepStartTime
        {
            get
            {
              if (!SubCriteria.ContainsKey("PerformedProcedureStepStartTime"))
              {
                 SubCriteria["PerformedProcedureStepStartTime"] = new SearchCondition<System.String>("PerformedProcedureStepStartTime");
              }
              return (ISearchCondition<System.String>)SubCriteria["PerformedProcedureStepStartTime"];
            } 
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Series", ColumnName="SeriesDescription")]
        public ISearchCondition<System.String> SeriesDescription
        {
            get
            {
              if (!SubCriteria.ContainsKey("SeriesDescription"))
              {
                 SubCriteria["SeriesDescription"] = new SearchCondition<System.String>("SeriesDescription");
              }
              return (ISearchCondition<System.String>)SubCriteria["SeriesDescription"];
            } 
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Series", ColumnName="SeriesInstanceUid")]
        public ISearchCondition<System.String> SeriesInstanceUid
        {
            get
            {
              if (!SubCriteria.ContainsKey("SeriesInstanceUid"))
              {
                 SubCriteria["SeriesInstanceUid"] = new SearchCondition<System.String>("SeriesInstanceUid");
              }
              return (ISearchCondition<System.String>)SubCriteria["SeriesInstanceUid"];
            } 
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Series", ColumnName="SeriesNumber")]
        public ISearchCondition<System.String> SeriesNumber
        {
            get
            {
              if (!SubCriteria.ContainsKey("SeriesNumber"))
              {
                 SubCriteria["SeriesNumber"] = new SearchCondition<System.String>("SeriesNumber");
              }
              return (ISearchCondition<System.String>)SubCriteria["SeriesNumber"];
            } 
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Series", ColumnName="ServerPartitionGUID")]
        public ISearchCondition<ClearCanvas.ImageServer.Enterprise.ServerEntityKey> ServerPartitionKey
        {
            get
            {
              if (!SubCriteria.ContainsKey("ServerPartitionKey"))
              {
                 SubCriteria["ServerPartitionKey"] = new SearchCondition<ClearCanvas.ImageServer.Enterprise.ServerEntityKey>("ServerPartitionKey");
              }
              return (ISearchCondition<ClearCanvas.ImageServer.Enterprise.ServerEntityKey>)SubCriteria["ServerPartitionKey"];
            } 
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Series", ColumnName="SourceApplicationEntityTitle")]
        public ISearchCondition<System.String> SourceApplicationEntityTitle
        {
            get
            {
              if (!SubCriteria.ContainsKey("SourceApplicationEntityTitle"))
              {
                 SubCriteria["SourceApplicationEntityTitle"] = new SearchCondition<System.String>("SourceApplicationEntityTitle");
              }
              return (ISearchCondition<System.String>)SubCriteria["SourceApplicationEntityTitle"];
            } 
        }
        [EntityFieldDatabaseMappingAttribute(TableName="Series", ColumnName="StudyGUID")]
        public ISearchCondition<ClearCanvas.ImageServer.Enterprise.ServerEntityKey> StudyKey
        {
            get
            {
              if (!SubCriteria.ContainsKey("StudyKey"))
              {
                 SubCriteria["StudyKey"] = new SearchCondition<ClearCanvas.ImageServer.Enterprise.ServerEntityKey>("StudyKey");
              }
              return (ISearchCondition<ClearCanvas.ImageServer.Enterprise.ServerEntityKey>)SubCriteria["StudyKey"];
            } 
        }
    }
}
