#region License

// Copyright (c) 2010, ClearCanvas Inc.
// All rights reserved.
// http://www.clearcanvas.ca
//
// This software is licensed under the Open Software License v3.0.
// For the complete license, see http://www.clearcanvas.ca/OSLv3.0

#endregion

// This file is auto-generated by the ClearCanvas.Model.SqlServer2005.CodeGenerator project.

namespace ClearCanvas.ImageServer.Model.EntityBrokers
{
    using System;
    using System.Xml;
    using ClearCanvas.ImageServer.Enterprise;

   public class ServerRuleUpdateColumns : EntityUpdateColumns
   {
       public ServerRuleUpdateColumns()
       : base("ServerRule")
       {}
        [EntityFieldDatabaseMappingAttribute(TableName="ServerRule", ColumnName="RuleName")]
        public String RuleName
        {
            set { SubParameters["RuleName"] = new EntityUpdateColumn<String>("RuleName", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="ServerRule", ColumnName="ServerPartitionGUID")]
        public ServerEntityKey ServerPartitionKey
        {
            set { SubParameters["ServerPartitionKey"] = new EntityUpdateColumn<ServerEntityKey>("ServerPartitionKey", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="ServerRule", ColumnName="ServerRuleTypeEnum")]
        public ServerRuleTypeEnum ServerRuleTypeEnum
        {
            set { SubParameters["ServerRuleTypeEnum"] = new EntityUpdateColumn<ServerRuleTypeEnum>("ServerRuleTypeEnum", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="ServerRule", ColumnName="ServerRuleApplyTimeEnum")]
        public ServerRuleApplyTimeEnum ServerRuleApplyTimeEnum
        {
            set { SubParameters["ServerRuleApplyTimeEnum"] = new EntityUpdateColumn<ServerRuleApplyTimeEnum>("ServerRuleApplyTimeEnum", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="ServerRule", ColumnName="Enabled")]
        public Boolean Enabled
        {
            set { SubParameters["Enabled"] = new EntityUpdateColumn<Boolean>("Enabled", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="ServerRule", ColumnName="DefaultRule")]
        public Boolean DefaultRule
        {
            set { SubParameters["DefaultRule"] = new EntityUpdateColumn<Boolean>("DefaultRule", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="ServerRule", ColumnName="ExemptRule")]
        public Boolean ExemptRule
        {
            set { SubParameters["ExemptRule"] = new EntityUpdateColumn<Boolean>("ExemptRule", value); }
        }
        [EntityFieldDatabaseMappingAttribute(TableName="ServerRule", ColumnName="RuleXml")]
        public XmlDocument RuleXml
        {
            set { SubParameters["RuleXml"] = new EntityUpdateColumn<XmlDocument>("RuleXml", value); }
        }
    }
}
