#region License

// Copyright (c) 2011, ClearCanvas Inc.
// All rights reserved.
// http://www.clearcanvas.ca
//
// This software is licensed under the Open Software License v3.0.
// For the complete license, see http://www.clearcanvas.ca/OSLv3.0

#endregion

using System;
using ClearCanvas.Common;

namespace ClearCanvas.ImageServer.Services.Common.Alert
{
    /// <summary>
    /// Defines the interface of a plugin that extends <see cref="AlertService"/>
    /// </summary>
    public interface IAlertServiceExtension
    {
        /// <summary>
        /// Called when an alert is generated.
        /// </summary>
        /// <param name="alert">The alert generated by the systems or applications</param>
        void OnAlert(ImageServer.Common.Alert alert);
    }

    /// <summary>
    /// Extension point of <see cref="AlertService"/>
    /// </summary>
    public class AlertServiceExtensionPoint : ExtensionPoint<IAlertServiceExtension> { }
}
