
using System;
using ClearCanvas.Common;

namespace ClearCanvas.ImageServer.Services.Common.Alert
{
    /// <summary>
    /// Defines the interface of a plugin that extends <see cref="AlertService"/>
    /// </summary>
    public interface IAlertServiceExtension
    {
        /// <summary>
        /// Called when an alert is generated.
        /// </summary>
        /// <param name="alert">The alert generated by the systems or applications</param>
        void OnAlert(ImageServer.Common.Alert alert);
    }

    /// <summary>
    /// Extension point of <see cref="AlertService"/>
    /// </summary>
    public class AlertServiceExtensionPoint : ExtensionPoint<IAlertServiceExtension> { }
}
