//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Annotations {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class AnnotationLayoutStoreSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AnnotationLayoutStoreSettings defaultInstance = ((AnnotationLayoutStoreSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AnnotationLayoutStoreSettings())));
        
        public static AnnotationLayoutStoreSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AnnotationLayoutStoreDefaults.xml")]
        public string LayoutSettingsXml {
            get {
                return ((string)(this["LayoutSettingsXml"]));
            }
            set {
                this["LayoutSettingsXml"] = value;
            }
        }
    }
}
